export type { IAuthUser, ITokens, IError } from './auth'

export type { IDetailedCity, IDetailedRegion, IDetailedCountry } from './detailed/country'
export type { IDetailedLesson, IDetailedSpecificLesson, IDetailedHomework } from './detailed/lesson'
export type { IDetailedModule, IDetailedManual, IDetailedTopic } from './detailed/manual'
export type { IDetailedParent, IDetailedStudent, IDetailedTeacher, IPersonHome } from './detailed/person'
export type { IDetailedKlass, IDetailedSchool, ISchoolWithKlasses, ISchoolWithTimetable } from './detailed/school'
export type { IDetailedUser, IUserRoutes } from './detailed/user'
export type { ICanEdit } from './detailed/canEdit'

export type { ICity, IRegion } from './listed/country'
export type { IHomework, ILessonTime, ILesson, INote, ISpecificLesson } from './listed/lesson'
export type { ITheory, ITask, IBalance, IModuleWithManual, IModule, IManual, ITopic } from './listed/manual'
export type { IParent, IStudent, IStudentWithKlass, ISubscription, ITeacher } from './listed/person'
export type { IKlass, IPosition, ISchool } from './listed/school'
export type { ISocial, IUser } from './listed/user'

export type { ICityName, IRegionName, ICountryName } from './name/country'
export type { ILessonTimeName, ILessonName, INoteName, ISpecificLessonName } from './name/lesson'
export type { IProgress } from './name/manual'
export type { IParentName, IStudentName, ITeacherName } from './name/person'
export type { IGroupName, IPositionName, ISchoolName, ISchoolNameWithTimetable, IKlassName, IKlassNameWithGroups } from './name/school'
export type { ISubjectName } from './name/subject'
export type { IUserName } from './name/user'

export type { IMedia, IDetailedMedia } from './media'