import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { Providers } from "./providers";
import { Stack } from "@mui/material";
import { SideBar } from "@/components";
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "AI School",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: React.ReactNode, params: Promise<{locale: string}> }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return <html lang={locale}>
    <body className={roboto.variable}>
      <NextIntlClientProvider>
        <Providers>
          <Stack direction='row' sx={{height: '100%'}}>
            <SideBar />
            <Stack id='main' sx={{flex: 1, height: '100%', bgcolor: 'background.paper', overflowY: 'auto', overscrollBehaviorY: 'auto'}}>
              {children}
            </Stack>
          </Stack>
        </Providers>
      </NextIntlClientProvider>
    </body>
  </html>
}